spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/crudProducer'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    error:
      include-stacktrace: on_param

logging:
  level:
    org:
      hibernate:
       SQL: debug
       type: trace